import { randomUUID } from "node:crypto";

/**
 * The two things every persisted record needs.
 *
 * §6 of the MVP brief asks for common lifecycle metadata used *consistently*,
 * not for one identical shape forced onto every domain. This is the whole of
 * the shared part: how an id is made and what "now" looks like. Everything else
 * about a record — which columns it has, what its status means — belongs to
 * the domain that owns it.
 *
 * §29 applies here in the negative: this is deliberately not the beginning of
 * a generic repository framework.
 */

/**
 * A new id, prefixed by what it identifies.
 *
 * `ev-9f3c…` rather than `9f3c…`, because an id that says what it is turns
 * every log line, URL and foreign key into something a person can read — and
 * makes a note id pasted into an event lookup fail loudly instead of quietly
 * finding nothing.
 *
 * Random rather than sequential: ids are generated by the application, so two
 * processes must never be able to agree on the same next number.
 */
export function newId(prefix: string): string {
  return `${prefix}-${randomUUID()}`;
}

/** Timestamps are full ISO 8601 in UTC. Domain *dates* stay `yyyy-MM-dd`. */
export function nowIso(): string {
  return new Date().toISOString();
}

/** Lifecycle columns, for the domains whose records want them. */
export interface RecordMeta {
  createdAt: string;
  updatedAt: string;
  /**
   * The person who created it — asserted, never verified. See
   * `src/domain/viewer.ts`. Present so that authorship survives into the
   * database; it is not, on its own, an access decision.
   */
  createdBy?: string;
}

/**
 * A record on its way into the database.
 *
 * At the storage boundary, "absent" and "explicitly undefined" mean the same
 * thing — both become NULL — so this relaxes `exactOptionalPropertyTypes` for
 * exactly that hop and nowhere else. Required fields stay required; only the
 * already-optional ones gain `| undefined`.
 *
 * Without it, every merge of a validated patch onto a stored record has to be
 * rebuilt key by key to satisfy a distinction the database does not have.
 */
export type Writable<T> = {
  [K in keyof T as undefined extends T[K] ? K : never]?: T[K] | undefined;
} & {
  [K in keyof T as undefined extends T[K] ? never : K]: T[K];
};
