/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountSecurityRouteImport } from './routes/account-security'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as CampusesRouteImport } from './routes/campuses'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeetingNotesRouteImport } from './routes/meeting-notes'
import { Route as MonthlyCalendarRouteImport } from './routes/monthly-calendar'
import { Route as MyProgressRouteImport } from './routes/my-progress'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as ProgressReportRouteImport } from './routes/progress-report'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResourceSearchRouteImport } from './routes/resource-search'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TeamRouteImport } from './routes/team'
import { Route as WeeklyAgendaRouteImport } from './routes/weekly-agenda'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents.$documentId'
import { Route as FormsIndexRouteImport } from './routes/forms.index'
import { Route as FormsFormIdRouteImport } from './routes/forms.$formId'
import { Route as GoalsIndexRouteImport } from './routes/goals.index'
import { Route as GoalsGoalIdRouteImport } from './routes/goals.$goalId'
import { Route as LeadershipReportsIndexRouteImport } from './routes/leadership-reports.index'
import { Route as LeadershipReportsReportIdRouteImport } from './routes/leadership-reports.$reportId'
import { Route as LeadershipIndexRouteImport } from './routes/leadership.index'
import { Route as LeadershipEntryIdRouteImport } from './routes/leadership.$entryId'
import { Route as LifegroupsIndexRouteImport } from './routes/lifegroups.index'
import { Route as LifegroupsGatheringIdRouteImport } from './routes/lifegroups.$gatheringId'
import { Route as MaintenanceRunRouteImport } from './routes/maintenance.run'
import { Route as MinistriesIndexRouteImport } from './routes/ministries.index'
import { Route as MinistriesMinistryIdRouteImport } from './routes/ministries.$ministryId'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeoplePersonIdRouteImport } from './routes/people.$personId'
import { Route as ReachOutIndexRouteImport } from './routes/reach-out.index'
import { Route as ReachOutReportIdRouteImport } from './routes/reach-out.$reportId'
import { Route as RecordsRecordIdRouteImport } from './routes/records.$recordId'
import { Route as WorkWorkIdRouteImport } from './routes/work.$workId'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'
import { Route as AuthGoogleStartRouteImport } from './routes/auth.google.start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/account-security',
  path: '/account-security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusesRoute = CampusesRouteImport.update({
  id: '/campuses',
  path: '/campuses',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingNotesRoute = MeetingNotesRouteImport.update({
  id: '/meeting-notes',
  path: '/meeting-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyCalendarRoute = MonthlyCalendarRouteImport.update({
  id: '/monthly-calendar',
  path: '/monthly-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProgressRoute = MyProgressRouteImport.update({
  id: '/my-progress',
  path: '/my-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressReportRoute = ProgressReportRouteImport.update({
  id: '/progress-report',
  path: '/progress-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceSearchRoute = ResourceSearchRouteImport.update({
  id: '/resource-search',
  path: '/resource-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyAgendaRoute = WeeklyAgendaRouteImport.update({
  id: '/weekly-agenda',
  path: '/weekly-agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIndexRoute = FormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdRoute = FormsFormIdRouteImport.update({
  id: '/forms/$formId',
  path: '/forms/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsIndexRoute = GoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsGoalIdRoute = GoalsGoalIdRouteImport.update({
  id: '/goals/$goalId',
  path: '/goals/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipReportsIndexRoute = LeadershipReportsIndexRouteImport.update({
  id: '/leadership-reports/',
  path: '/leadership-reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipReportsReportIdRoute =
  LeadershipReportsReportIdRouteImport.update({
    id: '/leadership-reports/$reportId',
    path: '/leadership-reports/$reportId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeadershipIndexRoute = LeadershipIndexRouteImport.update({
  id: '/leadership/',
  path: '/leadership/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipEntryIdRoute = LeadershipEntryIdRouteImport.update({
  id: '/leadership/$entryId',
  path: '/leadership/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)
const LifegroupsIndexRoute = LifegroupsIndexRouteImport.update({
  id: '/lifegroups/',
  path: '/lifegroups/',
  getParentRoute: () => rootRouteImport,
} as any)
const LifegroupsGatheringIdRoute = LifegroupsGatheringIdRouteImport.update({
  id: '/lifegroups/$gatheringId',
  path: '/lifegroups/$gatheringId',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRunRoute = MaintenanceRunRouteImport.update({
  id: '/maintenance/run',
  path: '/maintenance/run',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesIndexRoute = MinistriesIndexRouteImport.update({
  id: '/ministries/',
  path: '/ministries/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesMinistryIdRoute = MinistriesMinistryIdRouteImport.update({
  id: '/ministries/$ministryId',
  path: '/ministries/$ministryId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReachOutIndexRoute = ReachOutIndexRouteImport.update({
  id: '/reach-out/',
  path: '/reach-out/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReachOutReportIdRoute = ReachOutReportIdRouteImport.update({
  id: '/reach-out/$reportId',
  path: '/reach-out/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRecordIdRoute = RecordsRecordIdRouteImport.update({
  id: '/records/$recordId',
  path: '/records/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkWorkIdRoute = WorkWorkIdRouteImport.update({
  id: '/work/$workId',
  path: '/work/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleStartRoute = AuthGoogleStartRouteImport.update({
  id: '/auth/google/start',
  path: '/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-security': typeof AccountSecurityRoute
  '/administration': typeof AdministrationRoute
  '/attendance': typeof AttendanceRoute
  '/campuses': typeof CampusesRoute
  '/healthz': typeof HealthzRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/meeting-notes': typeof MeetingNotesRoute
  '/monthly-calendar': typeof MonthlyCalendarRoute
  '/my-progress': typeof MyProgressRoute
  '/planning': typeof PlanningRoute
  '/progress-report': typeof ProgressReportRoute
  '/reports': typeof ReportsRoute
  '/resource-search': typeof ResourceSearchRoute
  '/schedule': typeof ScheduleRoute
  '/setup': typeof SetupRoute
  '/team': typeof TeamRoute
  '/weekly-agenda': typeof WeeklyAgendaRoute
  '/welcome': typeof WelcomeRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/leadership-reports/$reportId': typeof LeadershipReportsReportIdRoute
  '/leadership/$entryId': typeof LeadershipEntryIdRoute
  '/lifegroups/$gatheringId': typeof LifegroupsGatheringIdRoute
  '/maintenance/run': typeof MaintenanceRunRoute
  '/ministries/$ministryId': typeof MinistriesMinistryIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/reach-out/$reportId': typeof ReachOutReportIdRoute
  '/records/$recordId': typeof RecordsRecordIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/documents/': typeof DocumentsIndexRoute
  '/forms/': typeof FormsIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/leadership-reports/': typeof LeadershipReportsIndexRoute
  '/leadership/': typeof LeadershipIndexRoute
  '/lifegroups/': typeof LifegroupsIndexRoute
  '/ministries/': typeof MinistriesIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/reach-out/': typeof ReachOutIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-security': typeof AccountSecurityRoute
  '/administration': typeof AdministrationRoute
  '/attendance': typeof AttendanceRoute
  '/campuses': typeof CampusesRoute
  '/healthz': typeof HealthzRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/meeting-notes': typeof MeetingNotesRoute
  '/monthly-calendar': typeof MonthlyCalendarRoute
  '/my-progress': typeof MyProgressRoute
  '/planning': typeof PlanningRoute
  '/progress-report': typeof ProgressReportRoute
  '/reports': typeof ReportsRoute
  '/resource-search': typeof ResourceSearchRoute
  '/schedule': typeof ScheduleRoute
  '/setup': typeof SetupRoute
  '/team': typeof TeamRoute
  '/weekly-agenda': typeof WeeklyAgendaRoute
  '/welcome': typeof WelcomeRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/leadership-reports/$reportId': typeof LeadershipReportsReportIdRoute
  '/leadership/$entryId': typeof LeadershipEntryIdRoute
  '/lifegroups/$gatheringId': typeof LifegroupsGatheringIdRoute
  '/maintenance/run': typeof MaintenanceRunRoute
  '/ministries/$ministryId': typeof MinistriesMinistryIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/reach-out/$reportId': typeof ReachOutReportIdRoute
  '/records/$recordId': typeof RecordsRecordIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/documents': typeof DocumentsIndexRoute
  '/forms': typeof FormsIndexRoute
  '/goals': typeof GoalsIndexRoute
  '/leadership-reports': typeof LeadershipReportsIndexRoute
  '/leadership': typeof LeadershipIndexRoute
  '/lifegroups': typeof LifegroupsIndexRoute
  '/ministries': typeof MinistriesIndexRoute
  '/people': typeof PeopleIndexRoute
  '/reach-out': typeof ReachOutIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-security': typeof AccountSecurityRoute
  '/administration': typeof AdministrationRoute
  '/attendance': typeof AttendanceRoute
  '/campuses': typeof CampusesRoute
  '/healthz': typeof HealthzRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/meeting-notes': typeof MeetingNotesRoute
  '/monthly-calendar': typeof MonthlyCalendarRoute
  '/my-progress': typeof MyProgressRoute
  '/planning': typeof PlanningRoute
  '/progress-report': typeof ProgressReportRoute
  '/reports': typeof ReportsRoute
  '/resource-search': typeof ResourceSearchRoute
  '/schedule': typeof ScheduleRoute
  '/setup': typeof SetupRoute
  '/team': typeof TeamRoute
  '/weekly-agenda': typeof WeeklyAgendaRoute
  '/welcome': typeof WelcomeRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/leadership-reports/$reportId': typeof LeadershipReportsReportIdRoute
  '/leadership/$entryId': typeof LeadershipEntryIdRoute
  '/lifegroups/$gatheringId': typeof LifegroupsGatheringIdRoute
  '/maintenance/run': typeof MaintenanceRunRoute
  '/ministries/$ministryId': typeof MinistriesMinistryIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/reach-out/$reportId': typeof ReachOutReportIdRoute
  '/records/$recordId': typeof RecordsRecordIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/documents/': typeof DocumentsIndexRoute
  '/forms/': typeof FormsIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/leadership-reports/': typeof LeadershipReportsIndexRoute
  '/leadership/': typeof LeadershipIndexRoute
  '/lifegroups/': typeof LifegroupsIndexRoute
  '/ministries/': typeof MinistriesIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/reach-out/': typeof ReachOutIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-security'
    | '/administration'
    | '/attendance'
    | '/campuses'
    | '/healthz'
    | '/inbox'
    | '/login'
    | '/meeting-notes'
    | '/monthly-calendar'
    | '/my-progress'
    | '/planning'
    | '/progress-report'
    | '/reports'
    | '/resource-search'
    | '/schedule'
    | '/setup'
    | '/team'
    | '/weekly-agenda'
    | '/welcome'
    | '/documents/$documentId'
    | '/forms/$formId'
    | '/goals/$goalId'
    | '/leadership-reports/$reportId'
    | '/leadership/$entryId'
    | '/lifegroups/$gatheringId'
    | '/maintenance/run'
    | '/ministries/$ministryId'
    | '/people/$personId'
    | '/reach-out/$reportId'
    | '/records/$recordId'
    | '/work/$workId'
    | '/documents/'
    | '/forms/'
    | '/goals/'
    | '/leadership-reports/'
    | '/leadership/'
    | '/lifegroups/'
    | '/ministries/'
    | '/people/'
    | '/reach-out/'
    | '/auth/google/callback'
    | '/auth/google/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-security'
    | '/administration'
    | '/attendance'
    | '/campuses'
    | '/healthz'
    | '/inbox'
    | '/login'
    | '/meeting-notes'
    | '/monthly-calendar'
    | '/my-progress'
    | '/planning'
    | '/progress-report'
    | '/reports'
    | '/resource-search'
    | '/schedule'
    | '/setup'
    | '/team'
    | '/weekly-agenda'
    | '/welcome'
    | '/documents/$documentId'
    | '/forms/$formId'
    | '/goals/$goalId'
    | '/leadership-reports/$reportId'
    | '/leadership/$entryId'
    | '/lifegroups/$gatheringId'
    | '/maintenance/run'
    | '/ministries/$ministryId'
    | '/people/$personId'
    | '/reach-out/$reportId'
    | '/records/$recordId'
    | '/work/$workId'
    | '/documents'
    | '/forms'
    | '/goals'
    | '/leadership-reports'
    | '/leadership'
    | '/lifegroups'
    | '/ministries'
    | '/people'
    | '/reach-out'
    | '/auth/google/callback'
    | '/auth/google/start'
  id:
    | '__root__'
    | '/'
    | '/account-security'
    | '/administration'
    | '/attendance'
    | '/campuses'
    | '/healthz'
    | '/inbox'
    | '/login'
    | '/meeting-notes'
    | '/monthly-calendar'
    | '/my-progress'
    | '/planning'
    | '/progress-report'
    | '/reports'
    | '/resource-search'
    | '/schedule'
    | '/setup'
    | '/team'
    | '/weekly-agenda'
    | '/welcome'
    | '/documents/$documentId'
    | '/forms/$formId'
    | '/goals/$goalId'
    | '/leadership-reports/$reportId'
    | '/leadership/$entryId'
    | '/lifegroups/$gatheringId'
    | '/maintenance/run'
    | '/ministries/$ministryId'
    | '/people/$personId'
    | '/reach-out/$reportId'
    | '/records/$recordId'
    | '/work/$workId'
    | '/documents/'
    | '/forms/'
    | '/goals/'
    | '/leadership-reports/'
    | '/leadership/'
    | '/lifegroups/'
    | '/ministries/'
    | '/people/'
    | '/reach-out/'
    | '/auth/google/callback'
    | '/auth/google/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AdministrationRoute: typeof AdministrationRoute
  AttendanceRoute: typeof AttendanceRoute
  CampusesRoute: typeof CampusesRoute
  HealthzRoute: typeof HealthzRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  MeetingNotesRoute: typeof MeetingNotesRoute
  MonthlyCalendarRoute: typeof MonthlyCalendarRoute
  MyProgressRoute: typeof MyProgressRoute
  PlanningRoute: typeof PlanningRoute
  ProgressReportRoute: typeof ProgressReportRoute
  ReportsRoute: typeof ReportsRoute
  ResourceSearchRoute: typeof ResourceSearchRoute
  ScheduleRoute: typeof ScheduleRoute
  SetupRoute: typeof SetupRoute
  TeamRoute: typeof TeamRoute
  WeeklyAgendaRoute: typeof WeeklyAgendaRoute
  WelcomeRoute: typeof WelcomeRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  FormsFormIdRoute: typeof FormsFormIdRoute
  GoalsGoalIdRoute: typeof GoalsGoalIdRoute
  LeadershipReportsReportIdRoute: typeof LeadershipReportsReportIdRoute
  LeadershipEntryIdRoute: typeof LeadershipEntryIdRoute
  LifegroupsGatheringIdRoute: typeof LifegroupsGatheringIdRoute
  MaintenanceRunRoute: typeof MaintenanceRunRoute
  MinistriesMinistryIdRoute: typeof MinistriesMinistryIdRoute
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  ReachOutReportIdRoute: typeof ReachOutReportIdRoute
  RecordsRecordIdRoute: typeof RecordsRecordIdRoute
  WorkWorkIdRoute: typeof WorkWorkIdRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  FormsIndexRoute: typeof FormsIndexRoute
  GoalsIndexRoute: typeof GoalsIndexRoute
  LeadershipReportsIndexRoute: typeof LeadershipReportsIndexRoute
  LeadershipIndexRoute: typeof LeadershipIndexRoute
  LifegroupsIndexRoute: typeof LifegroupsIndexRoute
  MinistriesIndexRoute: typeof MinistriesIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  ReachOutIndexRoute: typeof ReachOutIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthGoogleStartRoute: typeof AuthGoogleStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-security': {
      id: '/account-security'
      path: '/account-security'
      fullPath: '/account-security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campuses': {
      id: '/campuses'
      path: '/campuses'
      fullPath: '/campuses'
      preLoaderRoute: typeof CampusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-notes': {
      id: '/meeting-notes'
      path: '/meeting-notes'
      fullPath: '/meeting-notes'
      preLoaderRoute: typeof MeetingNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly-calendar': {
      id: '/monthly-calendar'
      path: '/monthly-calendar'
      fullPath: '/monthly-calendar'
      preLoaderRoute: typeof MonthlyCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-progress': {
      id: '/my-progress'
      path: '/my-progress'
      fullPath: '/my-progress'
      preLoaderRoute: typeof MyProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress-report': {
      id: '/progress-report'
      path: '/progress-report'
      fullPath: '/progress-report'
      preLoaderRoute: typeof ProgressReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource-search': {
      id: '/resource-search'
      path: '/resource-search'
      fullPath: '/resource-search'
      preLoaderRoute: typeof ResourceSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly-agenda': {
      id: '/weekly-agenda'
      path: '/weekly-agenda'
      fullPath: '/weekly-agenda'
      preLoaderRoute: typeof WeeklyAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/': {
      id: '/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof FormsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId': {
      id: '/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/forms/$formId'
      preLoaderRoute: typeof FormsFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/': {
      id: '/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof GoalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/$goalId': {
      id: '/goals/$goalId'
      path: '/goals/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof GoalsGoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership-reports/': {
      id: '/leadership-reports/'
      path: '/leadership-reports'
      fullPath: '/leadership-reports/'
      preLoaderRoute: typeof LeadershipReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership-reports/$reportId': {
      id: '/leadership-reports/$reportId'
      path: '/leadership-reports/$reportId'
      fullPath: '/leadership-reports/$reportId'
      preLoaderRoute: typeof LeadershipReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership/': {
      id: '/leadership/'
      path: '/leadership'
      fullPath: '/leadership/'
      preLoaderRoute: typeof LeadershipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership/$entryId': {
      id: '/leadership/$entryId'
      path: '/leadership/$entryId'
      fullPath: '/leadership/$entryId'
      preLoaderRoute: typeof LeadershipEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifegroups/': {
      id: '/lifegroups/'
      path: '/lifegroups'
      fullPath: '/lifegroups/'
      preLoaderRoute: typeof LifegroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifegroups/$gatheringId': {
      id: '/lifegroups/$gatheringId'
      path: '/lifegroups/$gatheringId'
      fullPath: '/lifegroups/$gatheringId'
      preLoaderRoute: typeof LifegroupsGatheringIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/run': {
      id: '/maintenance/run'
      path: '/maintenance/run'
      fullPath: '/maintenance/run'
      preLoaderRoute: typeof MaintenanceRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries/': {
      id: '/ministries/'
      path: '/ministries'
      fullPath: '/ministries/'
      preLoaderRoute: typeof MinistriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries/$ministryId': {
      id: '/ministries/$ministryId'
      path: '/ministries/$ministryId'
      fullPath: '/ministries/$ministryId'
      preLoaderRoute: typeof MinistriesMinistryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reach-out/': {
      id: '/reach-out/'
      path: '/reach-out'
      fullPath: '/reach-out/'
      preLoaderRoute: typeof ReachOutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reach-out/$reportId': {
      id: '/reach-out/$reportId'
      path: '/reach-out/$reportId'
      fullPath: '/reach-out/$reportId'
      preLoaderRoute: typeof ReachOutReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$recordId': {
      id: '/records/$recordId'
      path: '/records/$recordId'
      fullPath: '/records/$recordId'
      preLoaderRoute: typeof RecordsRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$workId': {
      id: '/work/$workId'
      path: '/work/$workId'
      fullPath: '/work/$workId'
      preLoaderRoute: typeof WorkWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/start': {
      id: '/auth/google/start'
      path: '/auth/google/start'
      fullPath: '/auth/google/start'
      preLoaderRoute: typeof AuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AdministrationRoute: AdministrationRoute,
  AttendanceRoute: AttendanceRoute,
  CampusesRoute: CampusesRoute,
  HealthzRoute: HealthzRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  MeetingNotesRoute: MeetingNotesRoute,
  MonthlyCalendarRoute: MonthlyCalendarRoute,
  MyProgressRoute: MyProgressRoute,
  PlanningRoute: PlanningRoute,
  ProgressReportRoute: ProgressReportRoute,
  ReportsRoute: ReportsRoute,
  ResourceSearchRoute: ResourceSearchRoute,
  ScheduleRoute: ScheduleRoute,
  SetupRoute: SetupRoute,
  TeamRoute: TeamRoute,
  WeeklyAgendaRoute: WeeklyAgendaRoute,
  WelcomeRoute: WelcomeRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  FormsFormIdRoute: FormsFormIdRoute,
  GoalsGoalIdRoute: GoalsGoalIdRoute,
  LeadershipReportsReportIdRoute: LeadershipReportsReportIdRoute,
  LeadershipEntryIdRoute: LeadershipEntryIdRoute,
  LifegroupsGatheringIdRoute: LifegroupsGatheringIdRoute,
  MaintenanceRunRoute: MaintenanceRunRoute,
  MinistriesMinistryIdRoute: MinistriesMinistryIdRoute,
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  ReachOutReportIdRoute: ReachOutReportIdRoute,
  RecordsRecordIdRoute: RecordsRecordIdRoute,
  WorkWorkIdRoute: WorkWorkIdRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  FormsIndexRoute: FormsIndexRoute,
  GoalsIndexRoute: GoalsIndexRoute,
  LeadershipReportsIndexRoute: LeadershipReportsIndexRoute,
  LeadershipIndexRoute: LeadershipIndexRoute,
  LifegroupsIndexRoute: LifegroupsIndexRoute,
  MinistriesIndexRoute: MinistriesIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  ReachOutIndexRoute: ReachOutIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthGoogleStartRoute: AuthGoogleStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
